//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visus.Cuid.Generator.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Visus.Cuid.Generator.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Error_GenerationInvalidValue {
            get {
                return ResourceManager.GetString("Error_GenerationInvalidValue", resourceCulture);
            }
        }
        
        internal static string Error_GenerationRequiresValue {
            get {
                return ResourceManager.GetString("Error_GenerationRequiresValue", resourceCulture);
            }
        }
        
        internal static string Error_LengthOutOfRange {
            get {
                return ResourceManager.GetString("Error_LengthOutOfRange", resourceCulture);
            }
        }
        
        internal static string Error_LengthRequiresValue {
            get {
                return ResourceManager.GetString("Error_LengthRequiresValue", resourceCulture);
            }
        }
        
        internal static string Error_NumberOutOfRange {
            get {
                return ResourceManager.GetString("Error_NumberOutOfRange", resourceCulture);
            }
        }
        
        internal static string Error_NumberRequiresValue {
            get {
                return ResourceManager.GetString("Error_NumberRequiresValue", resourceCulture);
            }
        }
        
        internal static string Error_UnrecognizedOption {
            get {
                return ResourceManager.GetString("Error_UnrecognizedOption", resourceCulture);
            }
        }
        
        internal static string Help_OptionsHeader {
            get {
                return ResourceManager.GetString("Help_OptionsHeader", resourceCulture);
            }
        }
        
        internal static string Help_Usage {
            get {
                return ResourceManager.GetString("Help_Usage", resourceCulture);
            }
        }
        
        internal static string HelpOpt_G_AllowedValues {
            get {
                return ResourceManager.GetString("HelpOpt_G_AllowedValues", resourceCulture);
            }
        }
        
        internal static string HelpOpt_G_DefaultValue {
            get {
                return ResourceManager.GetString("HelpOpt_G_DefaultValue", resourceCulture);
            }
        }
        
        internal static string HelpOpt_G_Descr {
            get {
                return ResourceManager.GetString("HelpOpt_G_Descr", resourceCulture);
            }
        }
        
        internal static string HelpOpt_H_Descr {
            get {
                return ResourceManager.GetString("HelpOpt_H_Descr", resourceCulture);
            }
        }
        
        internal static string HelpOpt_L_DefaultValue {
            get {
                return ResourceManager.GetString("HelpOpt_L_DefaultValue", resourceCulture);
            }
        }
        
        internal static string HelpOpt_L_Descr {
            get {
                return ResourceManager.GetString("HelpOpt_L_Descr", resourceCulture);
            }
        }
        
        internal static string HelpOpt_N_DefaultValue {
            get {
                return ResourceManager.GetString("HelpOpt_N_DefaultValue", resourceCulture);
            }
        }
        
        internal static string HelpOpt_N_Descr {
            get {
                return ResourceManager.GetString("HelpOpt_N_Descr", resourceCulture);
            }
        }
        
        internal static string HelpOpt_V_Descr {
            get {
                return ResourceManager.GetString("HelpOpt_V_Descr", resourceCulture);
            }
        }
    }
}
