blank_issues_enabled: false
contact_links:
  - name: cuidgen Community Support
    url: https://github.com/xaevik/cuidgen/discussions
    about: For general discussions, feature ideas, questions, and answers