name: Continuous Integration

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**/renovate.json' 
      - '.github/workflows/release.yaml'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**/renovate.json'
      - '.github/workflows/release.yaml'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: NuGet Cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: ${{ runner.os}}-nuget   
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - run: dotnet build -c release
          